////////////////////////////////
// BOTTOM DMG VAL GUIDE LOWER //
////////////////////////////////
"Resource/UI/HudDemomanCharge.res" //huntsman too - HudLayout.res
{	
	"Label_ChargeVal_50"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_50"
		"xpos" 				"4"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"12"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"50"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval"
	}
	"Label_ChargeVal_50_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_50_Shadow"
		"xpos" 				"4"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"12"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"50"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_60"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_60"
		"xpos" 				"19"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"12"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"60"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval"
	}
	"Label_ChargeVal_60_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_60_Shadow"
		"xpos" 				"19"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"12"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"60"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_70"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_70"
		"xpos" 				"33"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"12"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"70"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval"
	}
	"Label_ChargeVal_70_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_70_Shadow"
		"xpos" 				"33"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"12"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"70"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_80"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_80"
		"xpos" 				"47"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"12"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"80"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval"
	}
	"Label_ChargeVal_80_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_80_Shadow"
		"xpos" 				"47"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"12"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"80"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_90"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_90"
		"xpos" 				"61"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"12"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"90"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval"
	}
	"Label_ChargeVal_90_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_90_Shadow"
		"xpos" 				"61"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"12"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"90"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_100"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_100"
		"xpos" 				"74"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"100"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval"
	}
	"Label_ChargeVal_100_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_100_Shadow"
		"xpos" 				"74"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"100"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_110"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_110"
		"xpos" 				"88"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"110"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval"
	}
	"Label_ChargeVal_110_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_110_Shadow"
		"xpos" 				"88"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"110"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_120"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_120"
		"xpos" 				"103"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"120"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval"
	}
	"Label_ChargeVal_120_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_120_Shadow"
		"xpos" 				"103"
		"ypos" 				"18"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"120"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
}

//bind ctrl "toggle host_timescale 1 0.05"
//addcond 11/19