////////////////////////////////
// BOTTOM DMG VAL GUIDE UPPER //
////////////////////////////////
"Resource/UI/HudDemomanCharge.res" //huntsman too - HudLayout.res
{	
	"Label_ChargeVal_U_150_Crit"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_150_Crit"
		"xpos" 				"2"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"150"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_pip_crit"
	}
	"Label_ChargeVal_U_150_Crit_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_150_Crit_Shadow"
		"xpos" 				"2"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"150"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_U_175_Crit"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_175_Crit"
		"xpos" 				"14"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"175"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_pip_crit"
	}
	"Label_ChargeVal_U_175_Crit_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_175_Crit_Shadow"
		"xpos" 				"14"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"175"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_U_200_Crit"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_200_Crit"
		"xpos" 				"26"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"200"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"0"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_pip_crit"
	}
	"Label_ChargeVal_U_200_Crit_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_200_Crit_Shadow"
		"xpos" 				"26"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"200"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"0"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_U_125_MiniCrit"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_125_MiniCrit"
		"xpos" 				"62"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"125"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"0"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_minicrit"
	}
	"Label_ChargeVal_U_125_MiniCrit_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_125_MiniCrit_Shadow"
		"xpos" 				"62"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"125"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"0"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_U_300_Crit"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_300_Crit"
		"xpos" 				"73"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"300"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"0"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_pip_crit"
	}
	"Label_ChargeVal_U_300_Crit_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_300_Crit_Shadow"
		"xpos" 				"73"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"300"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"0"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_U_150_MiniCrit"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_150_MiniCrit"
		"xpos" 				"88"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"150"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"0"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_minicrit"
	}
	"Label_ChargeVal_U_150_MiniCrit_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_150_MiniCrit_Shadow"
		"xpos" 				"88"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"150"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"0"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
	
	"Label_ChargeVal_U_360_Crit"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_360_Crit"
		"xpos" 				"103"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"360"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_pip_crit"
	}
	"Label_ChargeVal_U_360_Crit_Shadow"
	{
		"ControlName" 		"CExLabel"
		"fieldName" 		"Label_ChargeVal_U_360_Crit_Shadow"
		"xpos" 				"103"
		"ypos" 				"0"
		"zpos" 				"3"
		"wide" 				"16"
		"tall" 				"8"
		"visible" 			"1"
		"visible_minmode" 	"0"
		"enabled" 			"1"
		"labelText" 		"360"
		"textAlignment" 	"center"
		"font" 			  	"font_bowdmgval_OLshadow"
		"textinsetx"		"3"
		"textinsety"		"-1"
		"fgcolor_override" 	"col_bowdmgval_shadow"
	}
}

//bind ctrl "toggle host_timescale 1 0.05"
//addcond 11/19